export const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ||
  "https://techbuds.online";

export const siteName = "TechBuds";

export const seoKeywords = [
  "TechBuds",
  "TechBuds Online",
  "TechBuds Digital Solutions",
  "TechBuds Technologies",
  "TechBuds Web Solutions",
  "TechBuds Software Solutions",
  "TechBuds Development Studio",
  "TechBuds Business Platforms",
  "TechBuds Creative Agency",
  "TechBuds Tech Company",
  "Software Solutions Company",
  "Digital Solutions Company",
  "Custom Web Development Company",
  "Mobile App Development Company",
  "Ecommerce Development Company",
  "Business Platform Development",
  "Web Application Development",
  "Website Development Services",
  "Scalable Digital Solutions",
  "Modern Web Solutions",
  "Software Solution Company in Bangalore",
  "Digital Solutions Company in Bangalore",
  "Web Development Company Bangalore",
  "Mobile App Development Bangalore",
  "Ecommerce Development Company Bangalore",
  "UI UX Design Company Bangalore",
  "Custom Software Development Bangalore",
  "Business Website Development Bangalore",
  "SEO Services Bangalore",
  "IT Solutions Company Bangalore",
  "Software Solution Company in Hyderabad",
  "Digital Solutions Company Hyderabad",
  "Web Development Company Hyderabad",
  "Mobile App Development Hyderabad",
  "Ecommerce Website Development Hyderabad",
  "Business Platform Development Hyderabad",
  "SEO Company Hyderabad",
  "Custom Software Company Hyderabad",
  "IT Services Company Hyderabad",
  "Scalable Web Solutions Hyderabad",
  "Brand Identity Design",
  "Logo Design Services",
  "Visual Branding Solutions",
  "Business Branding Agency",
  "Corporate Identity Design",
  "Modern Brand Design",
  "Startup Branding Services",
  "Digital Branding Company",
  "Creative Brand Strategy",
  "Professional Branding Solutions",
  "Custom Web Solutions",
  "Responsive Website Design",
  "Business Website Solutions",
  "Scalable Web Platforms",
  "Enterprise Web Solutions",
  "SaaS Platform Development",
  "Custom Dashboard Development",
  "Full Stack Development Services",
  "Android App Development",
  "iOS App Development",
  "Cross Platform App Development",
  "Flutter App Development",
  "Business Mobile Applications",
  "Enterprise Mobile Solutions",
  "Custom Mobile App Development",
  "Mobile UI UX Design",
  "Scalable Mobile Platforms",
  "CRM Development Services",
  "ERP Platform Solutions",
  "Workflow Automation Systems",
  "Business Management Software",
  "Admin Dashboard Development",
  "Enterprise Platform Development",
  "SaaS Business Platforms",
  "Operational Management Systems",
  "Business Automation Solutions",
  "SEO Services",
  "Technical SEO Optimization",
  "Website Performance Optimization",
  "Google Ranking Services",
  "Organic Traffic Growth",
  "SEO Optimization Company",
  "Core Web Vitals Optimization",
  "Search Engine Optimization Services",
  "Digital Growth Solutions",
  "Website Speed Optimization",
  "Ecommerce Website Development",
  "Online Store Development",
  "Q Commerce Platform Development",
  "Marketplace Development",
  "Ecommerce App Development",
  "Scalable Ecommerce Solutions",
  "Shopify Alternative Solutions",
  "Headless Ecommerce Development",
  "Digital Commerce Platforms",
  "Best Software Solution Company in Bangalore",
  "Best Digital Solutions Company in Hyderabad",
  "Affordable Web Development Company India",
  "Custom Business Platform Development Services",
  "Modern Ecommerce Website Development",
  "Mobile App Development for Startups",
  "SEO and Website Optimization Services",
  "Full Stack Development Company India",
  "Scalable Web Application Development",
  "Digital Transformation Solutions for Businesses",
  "Hire Web Development Company",
  "Hire Mobile App Developers",
  "Build Ecommerce Platform",
  "Develop Business Management Software",
  "Custom CRM Development",
  "Professional Branding Services",
  "SEO Services for Businesses",
  "Build Scalable Web Application",
  "Business Automation Development",
  "Enterprise Digital Solutions",
];

export const defaultSeo = {
  title: "TechBuds | Custom Websites, Apps, Branding and Digital Platforms",
  description:
    "TechBuds Online is a digital solutions company for custom web development, mobile apps, ecommerce platforms, branding, SEO, and scalable business platforms in Bangalore, Hyderabad, and remote.",
  image: "https://ik.imagekit.io/codebyjerry/techbuds/Hero%20web%20image.png",
  keywords: seoKeywords,
};

export const serviceSeo = [
  {
    slug: "brand-identity",
    title: "Brand Identity Services",
    description:
      "Build a memorable brand with TechBuds brand identity services, including logo systems, visual identity, typography, color palettes, and brand guidelines.",
    image: "https://ik.imagekit.io/codebyjerry/techbuds/brand_web.png",
  },
  {
    slug: "custom-web-solutions",
    title: "Custom Web Solutions",
    description:
      "Custom websites, web applications, dashboards, portals, and scalable web platforms built for performance, usability, and business growth.",
    image: "https://ik.imagekit.io/codebyjerry/techbuds/custom%20web%20desktop.png",
  },
  {
    slug: "mobile-applications",
    title: "Mobile Application Development",
    description:
      "Android, iOS, and cross-platform mobile applications with modern UI/UX, scalable backend systems, and business-focused workflows.",
    image: "https://ik.imagekit.io/codebyjerry/techbuds/mobile%20app%20desktop.png",
  },
  {
    slug: "business-platforms",
    title: "Business Platform Development",
    description:
      "Custom CRM, dashboards, workflow automation, portals, and business management platforms for scalable operations.",
    image: "https://ik.imagekit.io/codebyjerry/techbuds/business%20desktop.png",
  },
  {
    slug: "seo-growth",
    title: "SEO and Growth Services",
    description:
      "Technical SEO, performance optimization, content structure, analytics, and growth strategy for stronger organic visibility.",
    image: "https://ik.imagekit.io/codebyjerry/techbuds/seo%20desktop.png",
  },
  {
    slug: "ecommerce-digital",
    title: "Ecommerce Development Services",
    description:
      "Custom ecommerce websites, online stores, marketplaces, payment integrations, and digital commerce platforms built for conversion.",
    image: "https://ik.imagekit.io/codebyjerry/techbuds/ecommerce%20desktop.png",
  },
];

export function absoluteUrl(path = "/") {
  return `${siteUrl}${path.startsWith("/") ? path : `/${path}`}`;
}
